@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" UniqueAppointmentList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniqueAppointmentList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person


Person -up-> "*" Tag

Person --> Name
Person --> Phone
Person --> Email
Person --> Address

UniqueAppointmentList -down-> Appointment
Appointment --> AppointmentStatus
Appointment --> AppointmentDateTime
Appointment --> AppointmentLength
Appointment --> AppointmentId
Appointment --> AppointmentLocation
Appointment --> AppointmentType
Appointment --> AppointmentMessage

AppointmentStatus -[hidden]up-> AppointmentId
AppointmentDateTime -[hidden]up-> AppointmentLocation
AppointmentLength -[hidden]up-> AppointmentType
@enduml
